twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(APP_NAME)%'
        app_name_abbr: '%env(APP_NAME_ABBR)%'

when@test:
    twig:
        strict_variables: true
